# Generated by Django 4.2.13 on 2024-10-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mc_03',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('cod_dep', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=150, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('eess_nacido', models.CharField(blank=True, max_length=150, null=True)),
                ('ult_eess', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_doc', models.CharField(blank=True, max_length=20, null=True)),
                ('documento', models.CharField(blank=True, max_length=15, null=True)),
                ('ape_nombres', models.CharField(blank=True, max_length=200, null=True)),
                ('fec_nac', models.DateField(blank=True, null=True)),
                ('seguro', models.CharField(blank=True, max_length=30, null=True)),
                ('tmz', models.DateField(blank=True, null=True)),
                ('bcg', models.DateField(blank=True, null=True)),
                ('hvb', models.DateField(blank=True, null=True)),
                ('ctrl1', models.DateField(blank=True, null=True)),
                ('ctrl2', models.DateField(blank=True, null=True)),
                ('ctrl3', models.DateField(blank=True, null=True)),
                ('ctrl4', models.DateField(blank=True, null=True)),
                ('programa', models.CharField(blank=True, max_length=150, null=True)),
                ('den', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
