# Generated by Django 4.2.13 on 2024-10-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed2425', '0002_si_01'),
    ]

    operations = [
        migrations.CreateModel(
            name='si_0202',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('cod_sector', models.CharField(blank=True, max_length=10, null=True)),
                ('sector', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_dep', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('cod_eess', models.CharField(blank=True, max_length=10, null=True)),
                ('eess', models.CharField(blank=True, max_length=150, null=True)),
                ('ult_eess', models.CharField(blank=True, max_length=250, null=True)),
                ('documento', models.CharField(blank=True, max_length=15, null=True)),
                ('fec_nac', models.DateField(blank=True, null=True)),
                ('ape_nombres', models.CharField(blank=True, max_length=200, null=True)),
                ('seguro', models.CharField(blank=True, max_length=30, null=True)),
                ('dsje6m', models.DateField(blank=True, null=True)),
                ('suple1', models.DateField(blank=True, null=True)),
                ('suple2', models.DateField(blank=True, null=True)),
                ('suple2_1', models.DateField(blank=True, null=True)),
                ('dsje_ctrl1', models.DateField(blank=True, null=True)),
                ('suple3', models.DateField(blank=True, null=True)),
                ('suple3_1', models.DateField(blank=True, null=True)),
                ('dsje3', models.DateField(blank=True, null=True)),
                ('suple4', models.DateField(blank=True, null=True)),
                ('suple5', models.DateField(blank=True, null=True)),
                ('suple6', models.DateField(blank=True, null=True)),
                ('ta', models.DateField(blank=True, null=True)),
                ('ta_1', models.DateField(blank=True, null=True)),
                ('dsje_ctrl', models.DateField(blank=True, null=True)),
                ('programa', models.CharField(blank=True, max_length=150, null=True)),
                ('den', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
