# Generated by Django 4.2.13 on 2024-10-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed2425', '0005_si_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='vii_0101',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('cod_sector', models.CharField(blank=True, max_length=10, null=True)),
                ('sector', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_dep', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('categoria', models.CharField(blank=True, max_length=10, null=True)),
                ('eess_apn', models.CharField(blank=True, max_length=150, null=True)),
                ('eess_dx', models.CharField(blank=True, max_length=150, null=True)),
                ('documento', models.CharField(blank=True, max_length=15, null=True)),
                ('diagnostico', models.DateField(blank=True, null=True)),
                ('dx_3m', models.DateField(blank=True, null=True)),
                ('dx_6m', models.DateField(blank=True, null=True)),
                ('csm1', models.DateField(blank=True, null=True)),
                ('csm2', models.DateField(blank=True, null=True)),
                ('psicologia1', models.DateField(blank=True, null=True)),
                ('psicologia2', models.DateField(blank=True, null=True)),
                ('psicologia3', models.DateField(blank=True, null=True)),
                ('psicologia4', models.DateField(blank=True, null=True)),
                ('psicologia5', models.DateField(blank=True, null=True)),
                ('psicologia6', models.DateField(blank=True, null=True)),
                ('programa', models.CharField(blank=True, max_length=150, null=True)),
                ('den', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
