# Generated by Django 4.2.13 on 2024-10-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed2425', '0008_vi_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='si_0201_pr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('cod_sector', models.CharField(blank=True, max_length=10, null=True)),
                ('sector', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_dep', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('ult_eess', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_doc', models.CharField(blank=True, max_length=10, null=True)),
                ('documento', models.CharField(blank=True, max_length=15, null=True)),
                ('fec_nac', models.DateField(blank=True, null=True)),
                ('seguro', models.CharField(blank=True, max_length=30, null=True)),
                ('prematuro', models.IntegerField(blank=True, null=True)),
                ('visit7d', models.CharField(blank=True, max_length=150, null=True)),
                ('hb30d', models.DateField(blank=True, null=True)),
                ('suple1', models.DateField(blank=True, null=True)),
                ('suple2', models.DateField(blank=True, null=True)),
                ('suple3', models.DateField(blank=True, null=True)),
                ('dsje3m', models.DateField(blank=True, null=True)),
                ('suple4', models.DateField(blank=True, null=True)),
                ('visita4', models.DateField(blank=True, null=True)),
                ('suple5', models.DateField(blank=True, null=True)),
                ('visita5', models.DateField(blank=True, null=True)),
                ('dsje6m', models.DateField(blank=True, null=True)),
                ('ta6m', models.DateField(blank=True, null=True)),
                ('programa', models.CharField(blank=True, max_length=150, null=True)),
                ('den', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='si_0201_sn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('cod_sector', models.CharField(blank=True, max_length=10, null=True)),
                ('sector', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_dep', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('ult_eess', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_doc', models.CharField(blank=True, max_length=10, null=True)),
                ('documento', models.CharField(blank=True, max_length=15, null=True)),
                ('fec_nac', models.DateField(blank=True, null=True)),
                ('seguro', models.CharField(blank=True, max_length=30, null=True)),
                ('suple4', models.DateField(blank=True, null=True)),
                ('visita4', models.DateField(blank=True, null=True)),
                ('suple5', models.DateField(blank=True, null=True)),
                ('visita5', models.DateField(blank=True, null=True)),
                ('dsje6m', models.DateField(blank=True, null=True)),
                ('ta6m', models.DateField(blank=True, null=True)),
                ('programa', models.CharField(blank=True, max_length=150, null=True)),
                ('den', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
