# Generated by Django 4.2.13 on 2024-10-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed2425', '0009_si_0201_pr_si_0201_sn'),
    ]

    operations = [
        migrations.CreateModel(
            name='si_0201_cont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('cod_sector', models.CharField(blank=True, max_length=10, null=True)),
                ('sector', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_dep', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('seguro', models.CharField(blank=True, max_length=30, null=True)),
                ('den', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
