# Generated by Django 4.2.13 on 2024-10-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed2425', '0010_si_0201_cont'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc_03',
            name='num2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mc_03',
            name='visit7d_prom',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
