# Generated by Django 4.2.13 on 2024-10-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed2425', '0011_mc_03_num2_mc_03_visit7d_prom'),
    ]

    operations = [
        migrations.AddField(
            model_name='si_0202',
            name='dx_anemia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='si_0202',
            name='visista6',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='si_0202',
            name='visista8',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='si_0202',
            name='visista9',
            field=models.DateField(blank=True, null=True),
        ),
    ]
