# Generated by Django 4.2.13 on 2024-10-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed2425', '0012_si_0202_dx_anemia_si_0202_visista6_si_0202_visista8_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='si_0202',
            name='dsje4',
            field=models.DateField(blank=True, null=True),
        ),
    ]
