# Generated by Django 4.2.13 on 2024-10-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed2425', '0013_si_0202_dsje4'),
    ]

    operations = [
        migrations.AddField(
            model_name='si_0401',
            name='suple',
            field=models.DateField(blank=True, null=True),
        ),
    ]
