# Generated by Django 4.2.13 on 2024-10-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed2425', '0014_si_0401_suple'),
    ]

    operations = [
        migrations.AddField(
            model_name='si_0203',
            name='dsje12m',
            field=models.DateField(blank=True, null=True),
        ),
    ]
