# Generated by Django 4.2.13 on 2024-12-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed2425', '0015_si_0203_dsje12m'),
    ]

    operations = [
        migrations.CreateModel(
            name='si_03',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('cod_dep', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('ult_eess', models.CharField(blank=True, max_length=250, null=True)),
                ('documento', models.CharField(blank=True, max_length=15, null=True)),
                ('fec_nac', models.DateField(blank=True, null=True)),
                ('seguro', models.CharField(blank=True, max_length=30, null=True)),
                ('edias', models.IntegerField(blank=True, null=True)),
                ('emes', models.IntegerField(blank=True, null=True)),
                ('cred1', models.DateField(blank=True, null=True)),
                ('cred2', models.DateField(blank=True, null=True)),
                ('cred3', models.DateField(blank=True, null=True)),
                ('cred4', models.DateField(blank=True, null=True)),
                ('cred5', models.DateField(blank=True, null=True)),
                ('cred6', models.DateField(blank=True, null=True)),
                ('cred7', models.DateField(blank=True, null=True)),
                ('cred8', models.DateField(blank=True, null=True)),
                ('cred9', models.DateField(blank=True, null=True)),
                ('cred10', models.DateField(blank=True, null=True)),
                ('cred11', models.DateField(blank=True, null=True)),
                ('programa', models.CharField(blank=True, max_length=150, null=True)),
                ('den', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
