# Generated by Django 4.2.13 on 2024-10-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promsa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mat002_vg_n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('cod_dep', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('cod_eess', models.CharField(blank=True, max_length=10, null=True)),
                ('eess', models.CharField(blank=True, max_length=300, null=True)),
                ('documento', models.CharField(blank=True, max_length=20, null=True)),
                ('fec_atencion', models.DateField(blank=True, null=True)),
                ('lab', models.CharField(blank=True, max_length=10, null=True)),
                ('reg', models.CharField(blank=True, max_length=10, null=True)),
                ('trimestre', models.CharField(blank=True, max_length=50, null=True)),
                ('trazador', models.IntegerField(blank=True, null=True)),
                ('subproduct', models.CharField(blank=True, max_length=500, null=True)),
                ('den', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dit001_ac_n',
            name='reg',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
