# Generated by Django 4.2.13 on 2024-10-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promsa', '0002_mat002_vg_n_alter_dit001_ac_n_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='mat002_vg_c',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('cod_dep', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('den', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mat002_vg_cr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('cod_dep', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('eess', models.CharField(blank=True, max_length=300, null=True)),
                ('documento', models.CharField(blank=True, max_length=15, null=True)),
                ('primer_trim', models.DateField(blank=True, null=True)),
                ('segundo_trim', models.DateField(blank=True, null=True)),
                ('tercer_trim', models.DateField(blank=True, null=True)),
                ('trazador', models.IntegerField(blank=True, null=True)),
                ('fur', models.DateField(blank=True, null=True)),
                ('fpp', models.DateField(blank=True, null=True)),
                ('den', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
