# Generated by Django 4.2.13 on 2024-10-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promsa', '0004_mat002_dc_n'),
    ]

    operations = [
        migrations.CreateModel(
            name='dit001_fng_n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('cod_dep', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('cod_eess', models.CharField(blank=True, max_length=10, null=True)),
                ('eess', models.CharField(blank=True, max_length=300, null=True)),
                ('documento', models.CharField(blank=True, max_length=15, null=True)),
                ('edad_reg', models.IntegerField(blank=True, null=True)),
                ('tedad', models.CharField(blank=True, max_length=5, null=True)),
                ('subproduct', models.CharField(blank=True, max_length=500, null=True)),
                ('reg', models.CharField(blank=True, max_length=10, null=True)),
                ('den', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
