# Generated by Django 4.2.13 on 2024-10-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promsa', '0005_dit001_fng_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='dit001_fng_n',
            name='fec_nac',
            field=models.DateField(blank=True, null=True),
        ),
    ]
