# Generated by Django 4.2.13 on 2024-10-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promsa', '0006_dit001_fng_n_fec_nac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dit001_fng_n',
            old_name='fec_nac',
            new_name='fec_atencion',
        ),
    ]
