# Generated by Django 4.2.13 on 2024-10-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promsa', '0010_tbcvih016_vih_c_tbcvih016_vih_cr_tbcvih016_vih_n'),
    ]

    operations = [
        migrations.CreateModel(
            name='met017_met_cr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('cod_dep', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('documento', models.CharField(blank=True, max_length=15, null=True)),
                ('subproduct', models.CharField(blank=True, max_length=500, null=True)),
                ('reg', models.CharField(blank=True, max_length=20, null=True)),
                ('dengue1', models.DateField(blank=True, null=True)),
                ('dengue2', models.DateField(blank=True, null=True)),
                ('chikin1', models.DateField(blank=True, null=True)),
                ('chikin2', models.DateField(blank=True, null=True)),
                ('zoorabia1', models.DateField(blank=True, null=True)),
                ('zoorabia2', models.DateField(blank=True, null=True)),
                ('equino1', models.DateField(blank=True, null=True)),
                ('equino2', models.DateField(blank=True, null=True)),
                ('f_amar1', models.DateField(blank=True, null=True)),
                ('f_amar2', models.DateField(blank=True, null=True)),
                ('leishma1', models.DateField(blank=True, null=True)),
                ('leishma2', models.DateField(blank=True, null=True)),
                ('malaria1', models.DateField(blank=True, null=True)),
                ('malaria2', models.DateField(blank=True, null=True)),
                ('peste1', models.DateField(blank=True, null=True)),
                ('peste2', models.DateField(blank=True, null=True)),
                ('tifus1', models.DateField(blank=True, null=True)),
                ('tifus2', models.DateField(blank=True, null=True)),
                ('zika1', models.DateField(blank=True, null=True)),
                ('zika2', models.DateField(blank=True, null=True)),
                ('den', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='met017_met_n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('cod_dep', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('cod_eess', models.CharField(blank=True, max_length=10, null=True)),
                ('eess', models.CharField(blank=True, max_length=300, null=True)),
                ('documento', models.CharField(blank=True, max_length=15, null=True)),
                ('fec_atencion', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=50, null=True)),
                ('sesion', models.CharField(blank=True, max_length=30, null=True)),
                ('reg', models.CharField(blank=True, max_length=30, null=True)),
                ('subproduct', models.CharField(blank=True, max_length=500, null=True)),
                ('den', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
