# Generated by Django 4.2.13 on 2024-12-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fedgestante',
            name='si01',
        ),
        migrations.RemoveField(
            model_name='fedgestante',
            name='si04',
        ),
        migrations.RemoveField(
            model_name='fedgestante',
            name='vi0101',
        ),
        migrations.RemoveField(
            model_name='fedgestante',
            name='vi0102',
        ),
        migrations.RemoveField(
            model_name='fedgestante',
            name='vii01',
        ),
        migrations.RemoveField(
            model_name='fedninio',
            name='pqtrn',
        ),
        migrations.RemoveField(
            model_name='fedninio',
            name='si0201',
        ),
        migrations.RemoveField(
            model_name='fedninio',
            name='si0202',
        ),
        migrations.RemoveField(
            model_name='fedninio',
            name='si0203',
        ),
        migrations.RemoveField(
            model_name='fedninio',
            name='si03',
        ),
        migrations.AddField(
            model_name='fedgestante',
            name='den_si01',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fedgestante',
            name='den_si04',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fedgestante',
            name='den_vi0101',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fedgestante',
            name='den_vi0102',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fedgestante',
            name='den_vii01',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fedgestante',
            name='num_si01',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fedgestante',
            name='num_si04',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fedgestante',
            name='num_vi0101',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fedgestante',
            name='num_vi0102',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fedgestante',
            name='num_vii01',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fedninio',
            name='den_prn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fedninio',
            name='den_si0201',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fedninio',
            name='den_si0202',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fedninio',
            name='den_si0203',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fedninio',
            name='den_si03',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fedninio',
            name='num_prn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fedninio',
            name='num_si0201',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fedninio',
            name='num_si0202',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fedninio',
            name='num_si0203',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fedninio',
            name='num_si03',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
