# Generated by Django 4.2.13 on 2025-01-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='b1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('periodo', models.CharField(blank=True, max_length=7, null=True)),
                ('cod_dep', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('cod_eess', models.CharField(blank=True, max_length=10, null=True)),
                ('eess', models.CharField(blank=True, max_length=150, null=True)),
                ('cod_ipress', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_ugipress', models.CharField(blank=True, max_length=10, null=True)),
                ('sexo', models.IntegerField(blank=True, null=True)),
                ('gedad', models.IntegerField(blank=True, null=True)),
                ('aten_med', models.IntegerField(blank=True, null=True)),
                ('aten_nomed', models.IntegerField(blank=True, null=True)),
                ('aten_mes', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='b2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('periodo', models.CharField(blank=True, max_length=7, null=True)),
                ('cod_dep', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('cod_eess', models.CharField(blank=True, max_length=10, null=True)),
                ('eess', models.CharField(blank=True, max_length=150, null=True)),
                ('cod_ipress', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_ugipress', models.CharField(blank=True, max_length=10, null=True)),
                ('sexo', models.IntegerField(blank=True, null=True)),
                ('gedad', models.IntegerField(blank=True, null=True)),
                ('dx_def', models.CharField(blank=True, max_length=10, null=True)),
                ('aten', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
