# Generated by Django 4.2.13 on 2025-01-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setipress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b1',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='b1',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='b1',
            name='eess',
        ),
        migrations.RemoveField(
            model_name='b1',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='b2',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='b2',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='b2',
            name='eess',
        ),
        migrations.RemoveField(
            model_name='b2',
            name='provincia',
        ),
        migrations.AlterField(
            model_name='b1',
            name='aten_med',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='aten_mes',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='aten_nomed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='b2',
            name='aten',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
