# Generated by Django 4.2.13 on 2025-01-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setipress', '0002_remove_b1_departamento_remove_b1_distrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='b1',
            name='cod_dist2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='b2',
            name='cod_dist2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='cod_dep',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='b1',
            name='cod_prov',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='b2',
            name='aten',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='b2',
            name='cod_dep',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='b2',
            name='cod_prov',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
