# Generated by Django 4.2.13 on 2025-01-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setipress', '0003_b1_cod_dist2_b2_cod_dist2_alter_b1_cod_dep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='e',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('periodo', models.CharField(blank=True, max_length=7, null=True)),
                ('cod_dep', models.IntegerField(blank=True, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=5, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_eess', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_ipress', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_ugipress', models.CharField(blank=True, max_length=10, null=True)),
                ('tparto', models.CharField(blank=True, max_length=3, null=True)),
                ('complicacion', models.CharField(blank=True, max_length=8, null=True)),
                ('partos', models.CharField(blank=True, max_length=8, null=True)),
                ('t_nac', models.CharField(blank=True, max_length=8, null=True)),
                ('vivos', models.CharField(blank=True, max_length=8, null=True)),
                ('muertos', models.CharField(blank=True, max_length=8, null=True)),
                ('cod_dist2', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='f',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('periodo', models.CharField(blank=True, max_length=7, null=True)),
                ('cod_dep', models.IntegerField(blank=True, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=5, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_eess', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_ipress', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_ugipress', models.CharField(blank=True, max_length=10, null=True)),
                ('genero', models.IntegerField(blank=True, null=True)),
                ('gedad', models.CharField(blank=True, max_length=8, null=True)),
                ('eventos', models.CharField(blank=True, max_length=8, null=True)),
                ('total', models.CharField(blank=True, max_length=8, null=True)),
                ('cod_dist2', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
