from django.db import models

# Create your models here.
class fedninio(models.Model):
    cod_dep = models.CharField(max_length=5, blank=True, null=True)
    departamento = models.CharField(max_length=30, blank=True, null=True)
    cod_prov = models.CharField(max_length=5, blank=True, null=True)
    provincia = models.CharField(max_length=40, blank=True, null=True)
    cod_dist = models.CharField(max_length=8, blank=True, null=True)
    distrito = models.CharField(max_length=80, blank=True, null=True)
    anio = models.IntegerField(blank=True, null=True)
    mes = models.IntegerField(blank=True, null=True)
    nombremes = models.CharField(max_length=10, blank=True, null=True)
    den_prn = models.IntegerField(blank=True, null=True)
    num_prn = models.IntegerField(blank=True, null=True)
    den_si0201 = models.IntegerField(blank=True, null=True)
    num_si0201 = models.IntegerField(blank=True, null=True)
    den_si0202 = models.IntegerField(blank=True, null=True)
    num_si0202 = models.IntegerField(blank=True, null=True)
    den_si0203 = models.IntegerField(blank=True, null=True)
    num_si0203 = models.IntegerField(blank=True, null=True)
    den_si03 = models.IntegerField(blank=True, null=True)
    num_si03 = models.IntegerField(blank=True, null=True)


class fedgestante(models.Model):
    cod_dep = models.CharField(max_length=5, blank=True, null=True)
    departamento = models.CharField(max_length=30, blank=True, null=True)
    cod_prov = models.CharField(max_length=5, blank=True, null=True)
    provincia = models.CharField(max_length=40, blank=True, null=True)
    cod_dist = models.CharField(max_length=8, blank=True, null=True)
    distrito = models.CharField(max_length=80, blank=True, null=True)
    anio = models.IntegerField(blank=True, null=True)
    mes = models.IntegerField(blank=True, null=True)
    nombremes = models.CharField(max_length=10, blank=True, null=True)
    den_si04 = models.IntegerField(blank=True, null=True)
    num_si04 = models.IntegerField(blank=True, null=True)
    den_si01 = models.IntegerField(blank=True, null=True)
    num_si01 = models.IntegerField(blank=True, null=True)
    den_vi0101 = models.IntegerField(blank=True, null=True)
    num_vi0101 = models.IntegerField(blank=True, null=True)
    den_vi0102 = models.IntegerField(blank=True, null=True)
    num_vi0102 = models.IntegerField(blank=True, null=True)
    den_vii01 = models.IntegerField(blank=True, null=True)
    num_vii01 = models.IntegerField(blank=True, null=True)
