# Generated by Django 4.2.13 on 2024-10-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='actas_homol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_dep', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=150, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('ene', models.IntegerField(blank=True, null=True)),
                ('feb', models.IntegerField(blank=True, null=True)),
                ('mar', models.IntegerField(blank=True, null=True)),
                ('abr', models.IntegerField(blank=True, null=True)),
                ('may', models.IntegerField(blank=True, null=True)),
                ('jun', models.IntegerField(blank=True, null=True)),
                ('jul', models.IntegerField(blank=True, null=True)),
                ('ago', models.IntegerField(blank=True, null=True)),
                ('set', models.IntegerField(blank=True, null=True)),
                ('oct', models.IntegerField(blank=True, null=True)),
                ('nov', models.IntegerField(blank=True, null=True)),
                ('dic', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
