# Generated by Django 4.2.13 on 2024-10-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0002_actas_homol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padron_nom',
            name='eje_vial',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
