# Generated by Django 4.2.13 on 2024-10-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0003_alter_padron_nom_eje_vial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_dep', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento', models.CharField(blank=True, max_length=70, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=150, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('numdni', models.CharField(blank=True, max_length=15, null=True)),
                ('numcnv', models.CharField(blank=True, max_length=15, null=True)),
                ('documento', models.CharField(blank=True, max_length=15, null=True)),
                ('menor_encont', models.CharField(blank=True, max_length=30, null=True)),
                ('fec_nac', models.DateField(blank=True, null=True)),
                ('area_ccpp', models.CharField(blank=True, max_length=100, null=True)),
                ('eje_vial', models.CharField(blank=True, max_length=300, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('ref_direc', models.CharField(blank=True, max_length=300, null=True)),
                ('tseguro', models.CharField(blank=True, max_length=10, null=True)),
                ('seguro', models.CharField(blank=True, max_length=30, null=True)),
                ('tprog_social', models.CharField(blank=True, max_length=20, null=True)),
                ('est_regist', models.IntegerField(blank=True, null=True)),
                ('meses', models.IntegerField(blank=True, null=True)),
                ('mide', models.IntegerField(blank=True, null=True)),
                ('var_dni', models.IntegerField(blank=True, null=True)),
                ('var_direc', models.IntegerField(blank=True, null=True)),
                ('medicion', models.IntegerField(blank=True, null=True)),
                ('den', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
