# Generated by Django 4.2.13 on 2024-11-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0006_alter_plano_fmodific_alter_plano_fregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='id_pac',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
