# Generated by Django 4.2.13 on 2024-11-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0007_plano_anio_plano_id_pac'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='id_prof',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
