# Generated by Django 4.2.13 on 2024-11-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0008_plano_id_prof'),
    ]

    operations = [
        migrations.CreateModel(
            name='cnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_dep', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento', models.CharField(blank=True, max_length=40, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_eess', models.CharField(blank=True, max_length=15, null=True)),
                ('eess', models.CharField(blank=True, max_length=200, null=True)),
                ('cnv', models.CharField(blank=True, max_length=20, null=True)),
                ('institucion', models.CharField(blank=True, max_length=20, null=True)),
                ('categoria', models.CharField(blank=True, max_length=15, null=True)),
                ('periodo', models.CharField(blank=True, max_length=6, null=True)),
                ('fec_nac', models.DateField(blank=True, null=True)),
                ('peso', models.CharField(blank=True, max_length=6, null=True)),
                ('talla', models.CharField(blank=True, max_length=6, null=True)),
                ('apgar', models.IntegerField(blank=True, null=True)),
                ('dur_emb', models.IntegerField(blank=True, null=True)),
                ('cond_parto', models.CharField(blank=True, max_length=15, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('tparto', models.CharField(blank=True, max_length=10, null=True)),
                ('financiador', models.CharField(blank=True, max_length=20, null=True)),
                ('prof_cert', models.CharField(blank=True, max_length=30, null=True)),
                ('cert_prof', models.CharField(blank=True, max_length=30, null=True)),
                ('lugar_nac', models.CharField(blank=True, max_length=30, null=True)),
                ('est_civil', models.CharField(blank=True, max_length=15, null=True)),
                ('tdoc_madre', models.CharField(blank=True, max_length=25, null=True)),
                ('doc_madre', models.CharField(blank=True, max_length=15, null=True)),
                ('dpt_madre', models.CharField(blank=True, max_length=20, null=True)),
                ('prov_madre', models.CharField(blank=True, max_length=30, null=True)),
                ('dist_madre', models.CharField(blank=True, max_length=50, null=True)),
                ('fe_crea', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
